apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: nginx-ingress-controller
  repo: https://charts.bitnami.com/bitnami
  version: 8.0.1
  releaseName: nginx-ingress-controller
  valuesFile: values.yaml
