apps:
- autoUpdate: true
  name: dex
  repo: https://charts.dexidp.io
  private: false
  version: "*"
  system: kustomize
  paths:
  - base/resources/ops/dex/dev/kustomization.yaml
  containerImage: ignored
  containerVersionPrefix: ""
  repoUsername: ""
  repoPassword: ""
- autoUpdate: true
  name: oauth2-proxy
  repo: https://oauth2-proxy.github.io/manifests
  private: false
  version: "*"
  system: k8s
  paths:
  - base/patches/oauth2-proxy/dev/deployment.yaml
  containerImage: quay.io/oauth2-proxy/oauth2-proxy
  containerVersionPrefix: v
  repoUsername: ""
  repoPassword: ""
baseFolder: /Users/raf/dev/ops/rs-deployments
notify:
  enable: true
  webhook: from_env_var
  token: from_env_var
  channelId: ABCDEFGHIJ